### ISSUE TITLE
client cannot connect to pry-remote

### ISSUE THREAD

**Issue by wzin** [Mon-Ouie/pry-remote#11]
Server side : 
[pry-remote] Waiting for client on druby://0.0.0.0:9876

Client side : 

pry-remote --host server_addr.com -p 9876 -c -w

Server side then crashes with :

/home/app/shared/bundle/ruby/1.8/gems/pry-remote-0.1.0/lib/pry-remote.rb:167:in `remote_pry': $stderr must have write method, NilClass given (Typ
eError)                                                                                                                                                       
        from pry_remote.rb:5:in`initialize'
        from pry_remote.rb:9:in `new'
        from pry_remote.rb:9
        from /home/app/shared/bundle/ruby/1.8/gems/railties-3.0.10/lib/rails/commands.rb:39:in`eval'
        from /home/app/shared/bundle/ruby/1.8/gems/railties-3.0.10/lib/rails/commands/runner.rb:48
        from /home/app/shared/bundle/ruby/1.8/gems/railties-3.0.10/lib/rails/commands.rb:39:in `require'
        from /home/app/shared/bundle/ruby/1.8/gems/railties-3.0.10/lib/rails/commands.rb:39
        from script/rails:6:in`require'
        from script/rails:6

**Comment by JoseAlban** [comment]
+1 "$stderr must have write method, NilClass given", version 0.1.8
