### ISSUE TITLE
DRb::DRbConnError

### ISSUE THREAD

**Issue by julienXX** [Mon-Ouie/pry-remote#8]
Hi,
I'm trying to use pry-remote but I get:

$ be pry-remote  
/Users/julien/.rbenv/versions/1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:736:in `rescue in block in open': druby://localhost:9876 - #<Errno::ECONNREFUSED: Connection refused - connect(2)> (DRb::DRbConnError)
    from /Users/julien/.rbenv/versions/1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:730:in`block in open'
    from /Users/julien/.rbenv/versions/1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:729:in `each'
    from /Users/julien/.rbenv/versions/1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:729:in`open'
    from /Users/julien/.rbenv/versions/1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:1191:in `initialize'
    from /Users/julien/.rbenv/versions/1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:1171:in`new'
    from /Users/julien/.rbenv/versions/1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:1171:in `open'
    from /Users/julien/.rbenv/versions/1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:1087:in`block in method_missing'
    from /Users/julien/.rbenv/versions/1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:1105:in `with_friend'
    from /Users/julien/.rbenv/versions/1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:1086:in`method_missing'
    from /Users/julien/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/pry-remote-0.1.0/lib/pry-remote.rb:110:in `run'
    from /Users/julien/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/gems/pry-remote-0.1.0/bin/pry-remote:4:in`<top (required)>'
    from /Users/julien/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/bin/pry-remote:19:in `load'
    from /Users/julien/.rbenv/versions/1.9.3-p0/lib/ruby/gems/1.9.1/bin/pry-remote:19:in`<main>'

My environment is:
- rbenv 0.2.1
- ruby 1.9.3-p0 but I get the same error with 1.9.2-p290
- pow 0.3.2

Any idea what's going wrong?

Thanks,
Julien

**Comment by jducrot** [comment]
This might not help the masses but I am sure other n00bs (like me) will come to this page looking for this answer. I am running passenger on apache and I was getting the error pasted at the top of this thread. It's not enough to install the gem, you also have to include "require 'pry-remote'" in your main .rb file. Once I include that, add binding.remote-pry where you need it, run your call (which should pause) then enter pry-remote in the cli and voila!

**Comment by YOUConsulting** [comment]
Since I'm experiencing the same Issue and it's driving me mad because I can't debug I've also opened a StackOverflow topic for help!

Can we please combine forces and solve this problem?

All the information and logs that I have are mentioned in the following post:

http://stackoverflow.com/questions/32780971/pry-remote-not-triggered-rails-4

**Comment by jfedgar** [comment]
I had the same issues using Rails + Passenger + Apache. It turned out it was a conflict with pry-byebug (8.2.4). After I removed pry-byebug it worked fine.

**Comment by modullar** [comment]
I don't have `pry-byebug` installed and non of the solutions worked for me above!

**Comment by jaswinderahuja** [comment]
hit the API, if you feel api is stuck then from console type
> remote-pry
